spring:
  application:
    # 服务名
    name: yibao
  #freemarker配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates

server:
  port: 6533 # 服务端口


hdw:
  jwt:
    tokenHeader: Authorization #JWT存储的请求头
    tokenHead: Bearer  #JWT负载中拿到开头
    secret: sb-security #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24*7)
  # swagger配置
  swagger2:
    enabled: true
    description: 易宝支付
    title: 易宝支付
    version: 1.0

#易宝支付配置
#私钥
key:
#商家ID
p1MerId:
#商户密钥
keyValue:
#商户接收支付成功数据的地址
merchantCallbackURL:
  http://127.0.0.1:${server.port}/web/paymentResponse
